---
title: "Shiny Server"
author: "Edgar Ruiz"
date: "August 18, 2016"
output: html_document
---

### AWS/EC2 Setup

- Step 1- Amazon Machine Instance: **Ubuntu**

- Step 2 - Instance Type: **m4.large**

- Step 3 - No changes 

- Step 4 - Storage: **30 Size GiB**

- Step 5 - No changes

- Step 6 - Security Group Name: **Shiny** 

    Click Add Rule, select Type: **All Trafic** | Source: **My IP**
    
    **Optional: If you want to open your Shiny server to the world** - Click Add Rule, select Type: **Custom TCP Rule** | Port Range: **3838** |Source: **Anywhere**


- After clicking **Launch** the **"Select existing pair or create a new pair"** screen will appear, select:
  
      Create a new pair
      
      Key pair name: **shiny**
    
      Click **Download Key Pair**
      
      Save the file
      
      Click **Launch Instances**
      
- Go to the **Instances** section in the **EC2 Dashboard** section and click on the new instance

- Copy the **Public DNS** address, going forward referred to as **MY_PUBLIC_DNS**
  
### Key and Connection setup from laptop

AWS provides the step-by-step instructions for this part:

- Windows - http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/putty.html

       Complete sections **Converting Your Private Key Using PuTTYgen** and **Starting a PuTTY Session**

- Non-Windows - http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AccessingInstancesLinux.html

       Only go through the instructions in the **To connect to your instance using SSH** section

### Install R

We need to update the package list so that Ubuntu installs the latest R version.  Here is the reference: https://cran.r-project.org/bin/linux/ubuntu/

**Tip** The terminal commands inside the boxes can be copied and pasted into your terminal session.  In **putty** you can use right-click as the "paste" command.

```{}
sudo sh -c 'echo "deb http://cran.rstudio.com/bin/linux/ubuntu trusty/" >> /etc/apt/sources.list'
gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9
gpg -a --export E084DAB9 | sudo apt-key add -
sudo apt-get update
sudo apt-get install r-base
```

### Install Shiny

The steps below install the current version. To find updated instructions navigate to: https://www.rstudio.com/products/shiny/download-server/ and select **Ubuntu 12.04 or later**

```{}
sudo apt-get install gdebi-core
wget https://download3.rstudio.org/ubuntu-12.04/x86_64/shiny-server-1.4.4.801-amd64.deb
sudo gdebi shiny-server-1.4.4.801-amd64.deb
```


### Install RStudio

**Why install RStudio?** I'm using RStudio to upload and test my apps along with any other supporting files.  This removes the need to setup complicated security and FTP.

The steps below install the current version.  To find updated instructions navigate to: https://www.rstudio.com/products/rstudio/download-server/ and select **Debian/Ubuntu**

```{}
wget https://download2.rstudio.org/rstudio-server-0.99.903-amd64.deb
sudo gdebi rstudio-server-0.99.903-amd64.deb
sudo adduser rstudio
```
type **rstudio** as the password

### Pre-install needed packages

**Any package that an 'Shiny App' uses will need to be pre-installed, or the will crash**.  Here are a few we will load before we start using the server.  If you need any other package, just follow the instruction pattern, replacing the name of the desired package.

Alternatively, you could install the packages inside an RStudio session.  Using the terminal commands in this document would allow a non-R user to complete the full RStudio+Shiny installation without ever logging on to R.

```{}
sudo su - -c "R -e \"install.packages('rmarkdown', repos='http://cran.us.r-project.org')\""
sudo su - -c "R -e \"install.packages('ggvis', repos='http://cran.us.r-project.org')\""
sudo su - -c "R -e \"install.packages('ggplot2', repos='http://cran.us.r-project.org')\""
sudo su - -c "R -e \"install.packages('compat-gmp4', repos='http://cran.us.r-project.org')\""
sudo su - -c "R -e \"install.packages('compat-libffi5', repos='http://cran.us.r-project.org')\""
sudo su - -c "R -e \"install.packages('data.table', repos='http://cran.us.r-project.org')\""
sudo su - -c "R -e \"install.packages('ggplot2', repos='http://cran.us.r-project.org')\""
sudo su - -c "R -e \"install.packages('stats', repos='http://cran.us.r-project.org')\""
sudo su - -c "R -e \"install.packages('plyr', repos='http://cran.us.r-project.org')\""
sudo su - -c "R -e \"install.packages('maps', repos='http://cran.us.r-project.org')\""
sudo su - -c "R -e \"install.packages('stringr', repos='http://cran.us.r-project.org')\""
sudo su - -c "R -e \"install.packages('mapproj', repos='http://cran.us.r-project.org')\""
sudo su - -c "R -e \"install.packages('ggExtra', repos='http://cran.us.r-project.org')\""
sudo su - -c "R -e \"install.packages('ggthemes', repos='http://cran.us.r-project.org')\""
sudo su - -c "R -e \"install.packages('stats', repos='http://cran.us.r-project.org')\""
sudo su - -c "R -e \"install.packages('flexdashboard', repos='http://cran.us.r-project.org')\""
```

## Test the server

To confirm the **Shiny** server is working go to: http://MY_PUBLIC_DNS:3838/

To confirm the **RStudio** server is working go to: http://MY_PUBLIC_DNS:8787/
